name: Build and release native images

on:
  release:
    types: [created]

jobs:
  perform-release-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build native image with Gradle
      run: ./gradlew zipExecutable
    - name: Create Release
      id: create_release_linux
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_linux.outputs.upload_url }}  
        asset_path: ./build/dist/cross-compile-demo.zip
        asset_name: cross-compile-demo-linux_amd64.zip
        asset_content_type: application/zip
  perform-release-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build native image with Gradle
      run: ./gradlew zipExecutable
    - name: Create Release
      id: create_release_macos
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_macos.outputs.upload_url }}  
        asset_path: ./build/dist/cross-compile-demo.zip
        asset_name: cross-compile-demo-darwin_amd64.zip
        asset_content_type: application/zip